const kabupaten = [
  { id: 1101, provinsiId: 11, nama: "KABUPATEN SIMEULUE", createdAt: new Date(), updatedAt: new Date() },
  { id: 1102, provinsiId: 11, nama: "KABUPATEN ACEH SINGKIL", createdAt: new Date(), updatedAt: new Date() },
  { id: 1103, provinsiId: 11, nama: "KABUPATEN ACEH SELATAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 1104, provinsiId: 11, nama: "KABUPATEN ACEH TENGGARA", createdAt: new Date(), updatedAt: new Date() },
  { id: 1105, provinsiId: 11, nama: "KABUPATEN ACEH TIMUR", createdAt: new Date(), updatedAt: new Date() },
  { id: 1106, provinsiId: 11, nama: "KABUPATEN ACEH TENGAH", createdAt: new Date(), updatedAt: new Date() },
  { id: 1107, provinsiId: 11, nama: "KABUPATEN ACEH BARAT", createdAt: new Date(), updatedAt: new Date() },
  { id: 1108, provinsiId: 11, nama: "KABUPATEN ACEH BESAR", createdAt: new Date(), updatedAt: new Date() },
  { id: 1109, provinsiId: 11, nama: "KABUPATEN PIDIE", createdAt: new Date(), updatedAt: new Date() },
  { id: 1110, provinsiId: 11, nama: "KABUPATEN BIREUEN", createdAt: new Date(), updatedAt: new Date() },
  { id: 1111, provinsiId: 11, nama: "KABUPATEN ACEH UTARA", createdAt: new Date(), updatedAt: new Date() },
  { id: 1112, provinsiId: 11, nama: "KABUPATEN ACEH BARAT DAYA", createdAt: new Date(), updatedAt: new Date() },
  { id: 1113, provinsiId: 11, nama: "KABUPATEN GAYO LUES", createdAt: new Date(), updatedAt: new Date() },
  { id: 1114, provinsiId: 11, nama: "KABUPATEN ACEH TAMIANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 1115, provinsiId: 11, nama: "KABUPATEN NAGAN RAYA", createdAt: new Date(), updatedAt: new Date() },
  { id: 1116, provinsiId: 11, nama: "KABUPATEN ACEH JAYA", createdAt: new Date(), updatedAt: new Date() },
  { id: 1117, provinsiId: 11, nama: "KABUPATEN BENER MERIAH", createdAt: new Date(), updatedAt: new Date() },
  { id: 1118, provinsiId: 11, nama: "KABUPATEN PIDIE JAYA", createdAt: new Date(), updatedAt: new Date() },
  { id: 1171, provinsiId: 11, nama: "KOTA BANDA ACEH", createdAt: new Date(), updatedAt: new Date() },
  { id: 1172, provinsiId: 11, nama: "KOTA SABANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 1173, provinsiId: 11, nama: "KOTA LANGSA", createdAt: new Date(), updatedAt: new Date() },
  { id: 1174, provinsiId: 11, nama: "KOTA LHOKSEUMAWE", createdAt: new Date(), updatedAt: new Date() },
  { id: 1175, provinsiId: 11, nama: "KOTA SUBULUSSALAM", createdAt: new Date(), updatedAt: new Date() },
  { id: 1201, provinsiId: 12, nama: "KABUPATEN NIAS", createdAt: new Date(), updatedAt: new Date() },
  { id: 1202, provinsiId: 12, nama: "KABUPATEN MANDAILING NATAL", createdAt: new Date(), updatedAt: new Date() },
  { id: 1203, provinsiId: 12, nama: "KABUPATEN TAPANULI SELATAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 1204, provinsiId: 12, nama: "KABUPATEN TAPANULI TENGAH", createdAt: new Date(), updatedAt: new Date() },
  { id: 1205, provinsiId: 12, nama: "KABUPATEN TAPANULI UTARA", createdAt: new Date(), updatedAt: new Date() },
  { id: 1206, provinsiId: 12, nama: "KABUPATEN TOBA SAMOSIR", createdAt: new Date(), updatedAt: new Date() },
  { id: 1207, provinsiId: 12, nama: "KABUPATEN LABUHAN BATU", createdAt: new Date(), updatedAt: new Date() },
  { id: 1208, provinsiId: 12, nama: "KABUPATEN ASAHAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 1209, provinsiId: 12, nama: "KABUPATEN SIMALUNGUN", createdAt: new Date(), updatedAt: new Date() },
  { id: 1210, provinsiId: 12, nama: "KABUPATEN DAIRI", createdAt: new Date(), updatedAt: new Date() },
  { id: 1211, provinsiId: 12, nama: "KABUPATEN KARO", createdAt: new Date(), updatedAt: new Date() },
  { id: 1212, provinsiId: 12, nama: "KABUPATEN DELI SERDANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 1213, provinsiId: 12, nama: "KABUPATEN LANGKAT", createdAt: new Date(), updatedAt: new Date() },
  { id: 1214, provinsiId: 12, nama: "KABUPATEN NIAS SELATAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 1215, provinsiId: 12, nama: "KABUPATEN HUMBANG HASUNDUTAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 1216, provinsiId: 12, nama: "KABUPATEN PAKPAK BHARAT", createdAt: new Date(), updatedAt: new Date() },
  { id: 1217, provinsiId: 12, nama: "KABUPATEN SAMOSIR", createdAt: new Date(), updatedAt: new Date() },
  { id: 1218, provinsiId: 12, nama: "KABUPATEN SERDANG BEDAGAI", createdAt: new Date(), updatedAt: new Date() },
  { id: 1219, provinsiId: 12, nama: "KABUPATEN BATU BARA", createdAt: new Date(), updatedAt: new Date() },
  { id: 1220, provinsiId: 12, nama: "KABUPATEN PADANG LAWAS UTARA", createdAt: new Date(), updatedAt: new Date() },
  { id: 1221, provinsiId: 12, nama: "KABUPATEN PADANG LAWAS", createdAt: new Date(), updatedAt: new Date() },
  { id: 1222, provinsiId: 12, nama: "KABUPATEN LABUHAN BATU SELATAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 1223, provinsiId: 12, nama: "KABUPATEN LABUHAN BATU UTARA", createdAt: new Date(), updatedAt: new Date() },
  { id: 1224, provinsiId: 12, nama: "KABUPATEN NIAS UTARA", createdAt: new Date(), updatedAt: new Date() },
  { id: 1225, provinsiId: 12, nama: "KABUPATEN NIAS BARAT", createdAt: new Date(), updatedAt: new Date() },
  { id: 1271, provinsiId: 12, nama: "KOTA SIBOLGA", createdAt: new Date(), updatedAt: new Date() },
  { id: 1272, provinsiId: 12, nama: "KOTA TANJUNG BALAI", createdAt: new Date(), updatedAt: new Date() },
  { id: 1273, provinsiId: 12, nama: "KOTA PEMATANG SIANTAR", createdAt: new Date(), updatedAt: new Date() },
  { id: 1274, provinsiId: 12, nama: "KOTA TEBING TINGGI", createdAt: new Date(), updatedAt: new Date() },
  { id: 1275, provinsiId: 12, nama: "KOTA MEDAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 1276, provinsiId: 12, nama: "KOTA BINJAI", createdAt: new Date(), updatedAt: new Date() },
  { id: 1277, provinsiId: 12, nama: "KOTA PADANGSIDIMPUAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 1278, provinsiId: 12, nama: "KOTA GUNUNGSITOLI", createdAt: new Date(), updatedAt: new Date() },
  { id: 1301, provinsiId: 13, nama: "KABUPATEN KEPULAUAN MENTAWAI", createdAt: new Date(), updatedAt: new Date() },
  { id: 1302, provinsiId: 13, nama: "KABUPATEN PESISIR SELATAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 1303, provinsiId: 13, nama: "KABUPATEN SOLOK", createdAt: new Date(), updatedAt: new Date() },
  { id: 1304, provinsiId: 13, nama: "KABUPATEN SIJUNJUNG", createdAt: new Date(), updatedAt: new Date() },
  { id: 1305, provinsiId: 13, nama: "KABUPATEN TANAH DATAR", createdAt: new Date(), updatedAt: new Date() },
  { id: 1306, provinsiId: 13, nama: "KABUPATEN PADANG PARIAMAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 1307, provinsiId: 13, nama: "KABUPATEN AGAM", createdAt: new Date(), updatedAt: new Date() },
  { id: 1308, provinsiId: 13, nama: "KABUPATEN LIMA PULUH KOTA", createdAt: new Date(), updatedAt: new Date() },
  { id: 1309, provinsiId: 13, nama: "KABUPATEN PASAMAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 1310, provinsiId: 13, nama: "KABUPATEN SOLOK SELATAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 1311, provinsiId: 13, nama: "KABUPATEN DHARMASRAYA", createdAt: new Date(), updatedAt: new Date() },
  { id: 1312, provinsiId: 13, nama: "KABUPATEN PASAMAN BARAT", createdAt: new Date(), updatedAt: new Date() },
  { id: 1371, provinsiId: 13, nama: "KOTA PADANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 1372, provinsiId: 13, nama: "KOTA SOLOK", createdAt: new Date(), updatedAt: new Date() },
  { id: 1373, provinsiId: 13, nama: "KOTA SAWAH LUNTO", createdAt: new Date(), updatedAt: new Date() },
  { id: 1374, provinsiId: 13, nama: "KOTA PADANG PANJANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 1375, provinsiId: 13, nama: "KOTA BUKITTINGGI", createdAt: new Date(), updatedAt: new Date() },
  { id: 1376, provinsiId: 13, nama: "KOTA PAYAKUMBUH", createdAt: new Date(), updatedAt: new Date() },
  { id: 1377, provinsiId: 13, nama: "KOTA PARIAMAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 1401, provinsiId: 14, nama: "KABUPATEN KUANTAN SINGINGI", createdAt: new Date(), updatedAt: new Date() },
  { id: 1402, provinsiId: 14, nama: "KABUPATEN INDRAGIRI HULU", createdAt: new Date(), updatedAt: new Date() },
  { id: 1403, provinsiId: 14, nama: "KABUPATEN INDRAGIRI HILIR", createdAt: new Date(), updatedAt: new Date() },
  { id: 1404, provinsiId: 14, nama: "KABUPATEN PELALAWAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 1405, provinsiId: 14, nama: "KABUPATEN S I A K", createdAt: new Date(), updatedAt: new Date() },
  { id: 1406, provinsiId: 14, nama: "KABUPATEN KAMPAR", createdAt: new Date(), updatedAt: new Date() },
  { id: 1407, provinsiId: 14, nama: "KABUPATEN ROKAN HULU", createdAt: new Date(), updatedAt: new Date() },
  { id: 1408, provinsiId: 14, nama: "KABUPATEN BENGKALIS", createdAt: new Date(), updatedAt: new Date() },
  { id: 1409, provinsiId: 14, nama: "KABUPATEN ROKAN HILIR", createdAt: new Date(), updatedAt: new Date() },
  { id: 1410, provinsiId: 14, nama: "KABUPATEN KEPULAUAN MERANTI", createdAt: new Date(), updatedAt: new Date() },
  { id: 1471, provinsiId: 14, nama: "KOTA PEKANBARU", createdAt: new Date(), updatedAt: new Date() },
  { id: 1473, provinsiId: 14, nama: "KOTA D U M A I", createdAt: new Date(), updatedAt: new Date() },
  { id: 1501, provinsiId: 15, nama: "KABUPATEN KERINCI", createdAt: new Date(), updatedAt: new Date() },
  { id: 1502, provinsiId: 15, nama: "KABUPATEN MERANGIN", createdAt: new Date(), updatedAt: new Date() },
  { id: 1503, provinsiId: 15, nama: "KABUPATEN SAROLANGUN", createdAt: new Date(), updatedAt: new Date() },
  { id: 1504, provinsiId: 15, nama: "KABUPATEN BATANG HARI", createdAt: new Date(), updatedAt: new Date() },
  { id: 1505, provinsiId: 15, nama: "KABUPATEN MUARO JAMBI", createdAt: new Date(), updatedAt: new Date() },
  { id: 1506, provinsiId: 15, nama: "KABUPATEN TANJUNG JABUNG TIMUR", createdAt: new Date(), updatedAt: new Date() },
  { id: 1507, provinsiId: 15, nama: "KABUPATEN TANJUNG JABUNG BARAT", createdAt: new Date(), updatedAt: new Date() },
  { id: 1508, provinsiId: 15, nama: "KABUPATEN TEBO", createdAt: new Date(), updatedAt: new Date() },
  { id: 1509, provinsiId: 15, nama: "KABUPATEN BUNGO", createdAt: new Date(), updatedAt: new Date() },
  { id: 1571, provinsiId: 15, nama: "KOTA JAMBI", createdAt: new Date(), updatedAt: new Date() },
  { id: 1572, provinsiId: 15, nama: "KOTA SUNGAI PENUH", createdAt: new Date(), updatedAt: new Date() },
  { id: 1601, provinsiId: 16, nama: "KABUPATEN OGAN KOMERING ULU", createdAt: new Date(), updatedAt: new Date() },
  { id: 1602, provinsiId: 16, nama: "KABUPATEN OGAN KOMERING ILIR", createdAt: new Date(), updatedAt: new Date() },
  { id: 1603, provinsiId: 16, nama: "KABUPATEN MUARA ENIM", createdAt: new Date(), updatedAt: new Date() },
  { id: 1604, provinsiId: 16, nama: "KABUPATEN LAHAT", createdAt: new Date(), updatedAt: new Date() },
  { id: 1605, provinsiId: 16, nama: "KABUPATEN MUSI RAWAS", createdAt: new Date(), updatedAt: new Date() },
  { id: 1606, provinsiId: 16, nama: "KABUPATEN MUSI BANYUASIN", createdAt: new Date(), updatedAt: new Date() },
  { id: 1607, provinsiId: 16, nama: "KABUPATEN BANYU ASIN", createdAt: new Date(), updatedAt: new Date() },
  { id: 1608, provinsiId: 16, nama: "KABUPATEN OGAN KOMERING ULU SELATAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 1609, provinsiId: 16, nama: "KABUPATEN OGAN KOMERING ULU TIMUR", createdAt: new Date(), updatedAt: new Date() },
  { id: 1610, provinsiId: 16, nama: "KABUPATEN OGAN ILIR", createdAt: new Date(), updatedAt: new Date() },
  { id: 1611, provinsiId: 16, nama: "KABUPATEN EMPAT LAWANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 1612, provinsiId: 16, nama: "KABUPATEN PENUKAL ABAB LEMATANG ILIR", createdAt: new Date(), updatedAt: new Date() },
  { id: 1613, provinsiId: 16, nama: "KABUPATEN MUSI RAWAS UTARA", createdAt: new Date(), updatedAt: new Date() },
  { id: 1671, provinsiId: 16, nama: "KOTA PALEMBANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 1672, provinsiId: 16, nama: "KOTA PRABUMULIH", createdAt: new Date(), updatedAt: new Date() },
  { id: 1673, provinsiId: 16, nama: "KOTA PAGAR ALAM", createdAt: new Date(), updatedAt: new Date() },
  { id: 1674, provinsiId: 16, nama: "KOTA LUBUKLINGGAU", createdAt: new Date(), updatedAt: new Date() },
  { id: 1701, provinsiId: 17, nama: "KABUPATEN BENGKULU SELATAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 1702, provinsiId: 17, nama: "KABUPATEN REJANG LEBONG", createdAt: new Date(), updatedAt: new Date() },
  { id: 1703, provinsiId: 17, nama: "KABUPATEN BENGKULU UTARA", createdAt: new Date(), updatedAt: new Date() },
  { id: 1704, provinsiId: 17, nama: "KABUPATEN KAUR", createdAt: new Date(), updatedAt: new Date() },
  { id: 1705, provinsiId: 17, nama: "KABUPATEN SELUMA", createdAt: new Date(), updatedAt: new Date() },
  { id: 1706, provinsiId: 17, nama: "KABUPATEN MUKOMUKO", createdAt: new Date(), updatedAt: new Date() },
  { id: 1707, provinsiId: 17, nama: "KABUPATEN LEBONG", createdAt: new Date(), updatedAt: new Date() },
  { id: 1708, provinsiId: 17, nama: "KABUPATEN KEPAHIANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 1709, provinsiId: 17, nama: "KABUPATEN BENGKULU TENGAH", createdAt: new Date(), updatedAt: new Date() },
  { id: 1771, provinsiId: 17, nama: "KOTA BENGKULU", createdAt: new Date(), updatedAt: new Date() },
  { id: 1801, provinsiId: 18, nama: "KABUPATEN LAMPUNG BARAT", createdAt: new Date(), updatedAt: new Date() },
  { id: 1802, provinsiId: 18, nama: "KABUPATEN TANGGAMUS", createdAt: new Date(), updatedAt: new Date() },
  { id: 1803, provinsiId: 18, nama: "KABUPATEN LAMPUNG SELATAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 1804, provinsiId: 18, nama: "KABUPATEN LAMPUNG TIMUR", createdAt: new Date(), updatedAt: new Date() },
  { id: 1805, provinsiId: 18, nama: "KABUPATEN LAMPUNG TENGAH", createdAt: new Date(), updatedAt: new Date() },
  { id: 1806, provinsiId: 18, nama: "KABUPATEN LAMPUNG UTARA", createdAt: new Date(), updatedAt: new Date() },
  { id: 1807, provinsiId: 18, nama: "KABUPATEN WAY KANAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 1808, provinsiId: 18, nama: "KABUPATEN TULANGBAWANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 1809, provinsiId: 18, nama: "KABUPATEN PESAWARAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 1810, provinsiId: 18, nama: "KABUPATEN PRINGSEWU", createdAt: new Date(), updatedAt: new Date() },
  { id: 1811, provinsiId: 18, nama: "KABUPATEN MESUJI", createdAt: new Date(), updatedAt: new Date() },
  { id: 1812, provinsiId: 18, nama: "KABUPATEN TULANG BAWANG BARAT", createdAt: new Date(), updatedAt: new Date() },
  { id: 1813, provinsiId: 18, nama: "KABUPATEN PESISIR BARAT", createdAt: new Date(), updatedAt: new Date() },
  { id: 1871, provinsiId: 18, nama: "KOTA BANDAR LAMPUNG", createdAt: new Date(), updatedAt: new Date() },
  { id: 1872, provinsiId: 18, nama: "KOTA METRO", createdAt: new Date(), updatedAt: new Date() },
  { id: 1901, provinsiId: 19, nama: "KABUPATEN BANGKA", createdAt: new Date(), updatedAt: new Date() },
  { id: 1902, provinsiId: 19, nama: "KABUPATEN BELITUNG", createdAt: new Date(), updatedAt: new Date() },
  { id: 1903, provinsiId: 19, nama: "KABUPATEN BANGKA BARAT", createdAt: new Date(), updatedAt: new Date() },
  { id: 1904, provinsiId: 19, nama: "KABUPATEN BANGKA TENGAH", createdAt: new Date(), updatedAt: new Date() },
  { id: 1905, provinsiId: 19, nama: "KABUPATEN BANGKA SELATAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 1906, provinsiId: 19, nama: "KABUPATEN BELITUNG TIMUR", createdAt: new Date(), updatedAt: new Date() },
  { id: 1971, provinsiId: 19, nama: "KOTA PANGKAL PINANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 2101, provinsiId: 21, nama: "KABUPATEN KARIMUN", createdAt: new Date(), updatedAt: new Date() },
  { id: 2102, provinsiId: 21, nama: "KABUPATEN BINTAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 2103, provinsiId: 21, nama: "KABUPATEN NATUNA", createdAt: new Date(), updatedAt: new Date() },
  { id: 2104, provinsiId: 21, nama: "KABUPATEN LINGGA", createdAt: new Date(), updatedAt: new Date() },
  { id: 2105, provinsiId: 21, nama: "KABUPATEN KEPULAUAN ANAMBAS", createdAt: new Date(), updatedAt: new Date() },
  { id: 2171, provinsiId: 21, nama: "KOTA B A T A M", createdAt: new Date(), updatedAt: new Date() },
  { id: 2172, provinsiId: 21, nama: "KOTA TANJUNG PINANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 3101, provinsiId: 31, nama: "KABUPATEN KEPULAUAN SERIBU", createdAt: new Date(), updatedAt: new Date() },
  { id: 3171, provinsiId: 31, nama: "KOTA JAKARTA SELATAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 3172, provinsiId: 31, nama: "KOTA JAKARTA TIMUR", createdAt: new Date(), updatedAt: new Date() },
  { id: 3173, provinsiId: 31, nama: "KOTA JAKARTA PUSAT", createdAt: new Date(), updatedAt: new Date() },
  { id: 3174, provinsiId: 31, nama: "KOTA JAKARTA BARAT", createdAt: new Date(), updatedAt: new Date() },
  { id: 3175, provinsiId: 31, nama: "KOTA JAKARTA UTARA", createdAt: new Date(), updatedAt: new Date() },
  { id: 3201, provinsiId: 32, nama: "KABUPATEN BOGOR", createdAt: new Date(), updatedAt: new Date() },
  { id: 3202, provinsiId: 32, nama: "KABUPATEN SUKABUMI", createdAt: new Date(), updatedAt: new Date() },
  { id: 3203, provinsiId: 32, nama: "KABUPATEN CIANJUR", createdAt: new Date(), updatedAt: new Date() },
  { id: 3204, provinsiId: 32, nama: "KABUPATEN BANDUNG", createdAt: new Date(), updatedAt: new Date() },
  { id: 3205, provinsiId: 32, nama: "KABUPATEN GARUT", createdAt: new Date(), updatedAt: new Date() },
  { id: 3206, provinsiId: 32, nama: "KABUPATEN TASIKMALAYA", createdAt: new Date(), updatedAt: new Date() },
  { id: 3207, provinsiId: 32, nama: "KABUPATEN CIAMIS", createdAt: new Date(), updatedAt: new Date() },
  { id: 3208, provinsiId: 32, nama: "KABUPATEN KUNINGAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 3209, provinsiId: 32, nama: "KABUPATEN CIREBON", createdAt: new Date(), updatedAt: new Date() },
  { id: 3210, provinsiId: 32, nama: "KABUPATEN MAJALENGKA", createdAt: new Date(), updatedAt: new Date() },
  { id: 3211, provinsiId: 32, nama: "KABUPATEN SUMEDANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 3212, provinsiId: 32, nama: "KABUPATEN INDRAMAYU", createdAt: new Date(), updatedAt: new Date() },
  { id: 3213, provinsiId: 32, nama: "KABUPATEN SUBANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 3214, provinsiId: 32, nama: "KABUPATEN PURWAKARTA", createdAt: new Date(), updatedAt: new Date() },
  { id: 3215, provinsiId: 32, nama: "KABUPATEN KARAWANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 3216, provinsiId: 32, nama: "KABUPATEN BEKASI", createdAt: new Date(), updatedAt: new Date() },
  { id: 3217, provinsiId: 32, nama: "KABUPATEN BANDUNG BARAT", createdAt: new Date(), updatedAt: new Date() },
  { id: 3218, provinsiId: 32, nama: "KABUPATEN PANGANDARAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 3271, provinsiId: 32, nama: "KOTA BOGOR", createdAt: new Date(), updatedAt: new Date() },
  { id: 3272, provinsiId: 32, nama: "KOTA SUKABUMI", createdAt: new Date(), updatedAt: new Date() },
  { id: 3273, provinsiId: 32, nama: "KOTA BANDUNG", createdAt: new Date(), updatedAt: new Date() },
  { id: 3274, provinsiId: 32, nama: "KOTA CIREBON", createdAt: new Date(), updatedAt: new Date() },
  { id: 3275, provinsiId: 32, nama: "KOTA BEKASI", createdAt: new Date(), updatedAt: new Date() },
  { id: 3276, provinsiId: 32, nama: "KOTA DEPOK", createdAt: new Date(), updatedAt: new Date() },
  { id: 3277, provinsiId: 32, nama: "KOTA CIMAHI", createdAt: new Date(), updatedAt: new Date() },
  { id: 3278, provinsiId: 32, nama: "KOTA TASIKMALAYA", createdAt: new Date(), updatedAt: new Date() },
  { id: 3279, provinsiId: 32, nama: "KOTA BANJAR", createdAt: new Date(), updatedAt: new Date() },
  { id: 3301, provinsiId: 33, nama: "KABUPATEN CILACAP", createdAt: new Date(), updatedAt: new Date() },
  { id: 3302, provinsiId: 33, nama: "KABUPATEN BANYUMAS", createdAt: new Date(), updatedAt: new Date() },
  { id: 3303, provinsiId: 33, nama: "KABUPATEN PURBALINGGA", createdAt: new Date(), updatedAt: new Date() },
  { id: 3304, provinsiId: 33, nama: "KABUPATEN BANJARNEGARA", createdAt: new Date(), updatedAt: new Date() },
  { id: 3305, provinsiId: 33, nama: "KABUPATEN KEBUMEN", createdAt: new Date(), updatedAt: new Date() },
  { id: 3306, provinsiId: 33, nama: "KABUPATEN PURWOREJO", createdAt: new Date(), updatedAt: new Date() },
  { id: 3307, provinsiId: 33, nama: "KABUPATEN WONOSOBO", createdAt: new Date(), updatedAt: new Date() },
  { id: 3308, provinsiId: 33, nama: "KABUPATEN MAGELANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 3309, provinsiId: 33, nama: "KABUPATEN BOYOLALI", createdAt: new Date(), updatedAt: new Date() },
  { id: 3310, provinsiId: 33, nama: "KABUPATEN KLATEN", createdAt: new Date(), updatedAt: new Date() },
  { id: 3311, provinsiId: 33, nama: "KABUPATEN SUKOHARJO", createdAt: new Date(), updatedAt: new Date() },
  { id: 3312, provinsiId: 33, nama: "KABUPATEN WONOGIRI", createdAt: new Date(), updatedAt: new Date() },
  { id: 3313, provinsiId: 33, nama: "KABUPATEN KARANGANYAR", createdAt: new Date(), updatedAt: new Date() },
  { id: 3314, provinsiId: 33, nama: "KABUPATEN SRAGEN", createdAt: new Date(), updatedAt: new Date() },
  { id: 3315, provinsiId: 33, nama: "KABUPATEN GROBOGAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 3316, provinsiId: 33, nama: "KABUPATEN BLORA", createdAt: new Date(), updatedAt: new Date() },
  { id: 3317, provinsiId: 33, nama: "KABUPATEN REMBANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 3318, provinsiId: 33, nama: "KABUPATEN PATI", createdAt: new Date(), updatedAt: new Date() },
  { id: 3319, provinsiId: 33, nama: "KABUPATEN KUDUS", createdAt: new Date(), updatedAt: new Date() },
  { id: 3320, provinsiId: 33, nama: "KABUPATEN JEPARA", createdAt: new Date(), updatedAt: new Date() },
  { id: 3321, provinsiId: 33, nama: "KABUPATEN DEMAK", createdAt: new Date(), updatedAt: new Date() },
  { id: 3322, provinsiId: 33, nama: "KABUPATEN SEMARANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 3323, provinsiId: 33, nama: "KABUPATEN TEMANGGUNG", createdAt: new Date(), updatedAt: new Date() },
  { id: 3324, provinsiId: 33, nama: "KABUPATEN KENDAL", createdAt: new Date(), updatedAt: new Date() },
  { id: 3325, provinsiId: 33, nama: "KABUPATEN BATANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 3326, provinsiId: 33, nama: "KABUPATEN PEKALONGAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 3327, provinsiId: 33, nama: "KABUPATEN PEMALANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 3328, provinsiId: 33, nama: "KABUPATEN TEGAL", createdAt: new Date(), updatedAt: new Date() },
  { id: 3329, provinsiId: 33, nama: "KABUPATEN BREBES", createdAt: new Date(), updatedAt: new Date() },
  { id: 3371, provinsiId: 33, nama: "KOTA MAGELANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 3372, provinsiId: 33, nama: "KOTA SURAKARTA", createdAt: new Date(), updatedAt: new Date() },
  { id: 3373, provinsiId: 33, nama: "KOTA SALATIGA", createdAt: new Date(), updatedAt: new Date() },
  { id: 3374, provinsiId: 33, nama: "KOTA SEMARANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 3375, provinsiId: 33, nama: "KOTA PEKALONGAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 3376, provinsiId: 33, nama: "KOTA TEGAL", createdAt: new Date(), updatedAt: new Date() },
  { id: 3401, provinsiId: 34, nama: "KABUPATEN KULON PROGO", createdAt: new Date(), updatedAt: new Date() },
  { id: 3402, provinsiId: 34, nama: "KABUPATEN BANTUL", createdAt: new Date(), updatedAt: new Date() },
  { id: 3403, provinsiId: 34, nama: "KABUPATEN GUNUNG KIDUL", createdAt: new Date(), updatedAt: new Date() },
  { id: 3404, provinsiId: 34, nama: "KABUPATEN SLEMAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 3471, provinsiId: 34, nama: "KOTA YOGYAKARTA", createdAt: new Date(), updatedAt: new Date() },
  { id: 3501, provinsiId: 35, nama: "KABUPATEN PACITAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 3502, provinsiId: 35, nama: "KABUPATEN PONOROGO", createdAt: new Date(), updatedAt: new Date() },
  { id: 3503, provinsiId: 35, nama: "KABUPATEN TRENGGALEK", createdAt: new Date(), updatedAt: new Date() },
  { id: 3504, provinsiId: 35, nama: "KABUPATEN TULUNGAGUNG", createdAt: new Date(), updatedAt: new Date() },
  { id: 3505, provinsiId: 35, nama: "KABUPATEN BLITAR", createdAt: new Date(), updatedAt: new Date() },
  { id: 3506, provinsiId: 35, nama: "KABUPATEN KEDIRI", createdAt: new Date(), updatedAt: new Date() },
  { id: 3507, provinsiId: 35, nama: "KABUPATEN MALANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 3508, provinsiId: 35, nama: "KABUPATEN LUMAJANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 3509, provinsiId: 35, nama: "KABUPATEN JEMBER", createdAt: new Date(), updatedAt: new Date() },
  { id: 3510, provinsiId: 35, nama: "KABUPATEN BANYUWANGI", createdAt: new Date(), updatedAt: new Date() },
  { id: 3511, provinsiId: 35, nama: "KABUPATEN BONDOWOSO", createdAt: new Date(), updatedAt: new Date() },
  { id: 3512, provinsiId: 35, nama: "KABUPATEN SITUBONDO", createdAt: new Date(), updatedAt: new Date() },
  { id: 3513, provinsiId: 35, nama: "KABUPATEN PROBOLINGGO", createdAt: new Date(), updatedAt: new Date() },
  { id: 3514, provinsiId: 35, nama: "KABUPATEN PASURUAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 3515, provinsiId: 35, nama: "KABUPATEN SIDOARJO", createdAt: new Date(), updatedAt: new Date() },
  { id: 3516, provinsiId: 35, nama: "KABUPATEN MOJOKERTO", createdAt: new Date(), updatedAt: new Date() },
  { id: 3517, provinsiId: 35, nama: "KABUPATEN JOMBANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 3518, provinsiId: 35, nama: "KABUPATEN NGANJUK", createdAt: new Date(), updatedAt: new Date() },
  { id: 3519, provinsiId: 35, nama: "KABUPATEN MADIUN", createdAt: new Date(), updatedAt: new Date() },
  { id: 3520, provinsiId: 35, nama: "KABUPATEN MAGETAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 3521, provinsiId: 35, nama: "KABUPATEN NGAWI", createdAt: new Date(), updatedAt: new Date() },
  { id: 3522, provinsiId: 35, nama: "KABUPATEN BOJONEGORO", createdAt: new Date(), updatedAt: new Date() },
  { id: 3523, provinsiId: 35, nama: "KABUPATEN TUBAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 3524, provinsiId: 35, nama: "KABUPATEN LAMONGAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 3525, provinsiId: 35, nama: "KABUPATEN GRESIK", createdAt: new Date(), updatedAt: new Date() },
  { id: 3526, provinsiId: 35, nama: "KABUPATEN BANGKALAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 3527, provinsiId: 35, nama: "KABUPATEN SAMPANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 3528, provinsiId: 35, nama: "KABUPATEN PAMEKASAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 3529, provinsiId: 35, nama: "KABUPATEN SUMENEP", createdAt: new Date(), updatedAt: new Date() },
  { id: 3571, provinsiId: 35, nama: "KOTA KEDIRI", createdAt: new Date(), updatedAt: new Date() },
  { id: 3572, provinsiId: 35, nama: "KOTA BLITAR", createdAt: new Date(), updatedAt: new Date() },
  { id: 3573, provinsiId: 35, nama: "KOTA MALANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 3574, provinsiId: 35, nama: "KOTA PROBOLINGGO", createdAt: new Date(), updatedAt: new Date() },
  { id: 3575, provinsiId: 35, nama: "KOTA PASURUAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 3576, provinsiId: 35, nama: "KOTA MOJOKERTO", createdAt: new Date(), updatedAt: new Date() },
  { id: 3577, provinsiId: 35, nama: "KOTA MADIUN", createdAt: new Date(), updatedAt: new Date() },
  { id: 3578, provinsiId: 35, nama: "KOTA SURABAYA", createdAt: new Date(), updatedAt: new Date() },
  { id: 3579, provinsiId: 35, nama: "KOTA BATU", createdAt: new Date(), updatedAt: new Date() },
  { id: 3601, provinsiId: 36, nama: "KABUPATEN PANDEGLANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 3602, provinsiId: 36, nama: "KABUPATEN LEBAK", createdAt: new Date(), updatedAt: new Date() },
  { id: 3603, provinsiId: 36, nama: "KABUPATEN TANGERANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 3604, provinsiId: 36, nama: "KABUPATEN SERANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 3671, provinsiId: 36, nama: "KOTA TANGERANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 3672, provinsiId: 36, nama: "KOTA CILEGON", createdAt: new Date(), updatedAt: new Date() },
  { id: 3673, provinsiId: 36, nama: "KOTA SERANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 3674, provinsiId: 36, nama: "KOTA TANGERANG SELATAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 5101, provinsiId: 51, nama: "KABUPATEN JEMBRANA", createdAt: new Date(), updatedAt: new Date() },
  { id: 5102, provinsiId: 51, nama: "KABUPATEN TABANAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 5103, provinsiId: 51, nama: "KABUPATEN BADUNG", createdAt: new Date(), updatedAt: new Date() },
  { id: 5104, provinsiId: 51, nama: "KABUPATEN GIANYAR", createdAt: new Date(), updatedAt: new Date() },
  { id: 5105, provinsiId: 51, nama: "KABUPATEN KLUNGKUNG", createdAt: new Date(), updatedAt: new Date() },
  { id: 5106, provinsiId: 51, nama: "KABUPATEN BANGLI", createdAt: new Date(), updatedAt: new Date() },
  { id: 5107, provinsiId: 51, nama: "KABUPATEN KARANG ASEM", createdAt: new Date(), updatedAt: new Date() },
  { id: 5108, provinsiId: 51, nama: "KABUPATEN BULELENG", createdAt: new Date(), updatedAt: new Date() },
  { id: 5171, provinsiId: 51, nama: "KOTA DENPASAR", createdAt: new Date(), updatedAt: new Date() },
  { id: 5201, provinsiId: 52, nama: "KABUPATEN LOMBOK BARAT", createdAt: new Date(), updatedAt: new Date() },
  { id: 5202, provinsiId: 52, nama: "KABUPATEN LOMBOK TENGAH", createdAt: new Date(), updatedAt: new Date() },
  { id: 5203, provinsiId: 52, nama: "KABUPATEN LOMBOK TIMUR", createdAt: new Date(), updatedAt: new Date() },
  { id: 5204, provinsiId: 52, nama: "KABUPATEN SUMBAWA", createdAt: new Date(), updatedAt: new Date() },
  { id: 5205, provinsiId: 52, nama: "KABUPATEN DOMPU", createdAt: new Date(), updatedAt: new Date() },
  { id: 5206, provinsiId: 52, nama: "KABUPATEN BIMA", createdAt: new Date(), updatedAt: new Date() },
  { id: 5207, provinsiId: 52, nama: "KABUPATEN SUMBAWA BARAT", createdAt: new Date(), updatedAt: new Date() },
  { id: 5208, provinsiId: 52, nama: "KABUPATEN LOMBOK UTARA", createdAt: new Date(), updatedAt: new Date() },
  { id: 5271, provinsiId: 52, nama: "KOTA MATARAM", createdAt: new Date(), updatedAt: new Date() },
  { id: 5272, provinsiId: 52, nama: "KOTA BIMA", createdAt: new Date(), updatedAt: new Date() },
  { id: 5301, provinsiId: 53, nama: "KABUPATEN SUMBA BARAT", createdAt: new Date(), updatedAt: new Date() },
  { id: 5302, provinsiId: 53, nama: "KABUPATEN SUMBA TIMUR", createdAt: new Date(), updatedAt: new Date() },
  { id: 5303, provinsiId: 53, nama: "KABUPATEN KUPANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 5304, provinsiId: 53, nama: "KABUPATEN TIMOR TENGAH SELATAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 5305, provinsiId: 53, nama: "KABUPATEN TIMOR TENGAH UTARA", createdAt: new Date(), updatedAt: new Date() },
  { id: 5306, provinsiId: 53, nama: "KABUPATEN BELU", createdAt: new Date(), updatedAt: new Date() },
  { id: 5307, provinsiId: 53, nama: "KABUPATEN ALOR", createdAt: new Date(), updatedAt: new Date() },
  { id: 5308, provinsiId: 53, nama: "KABUPATEN LEMBATA", createdAt: new Date(), updatedAt: new Date() },
  { id: 5309, provinsiId: 53, nama: "KABUPATEN FLORES TIMUR", createdAt: new Date(), updatedAt: new Date() },
  { id: 5310, provinsiId: 53, nama: "KABUPATEN SIKKA", createdAt: new Date(), updatedAt: new Date() },
  { id: 5311, provinsiId: 53, nama: "KABUPATEN ENDE", createdAt: new Date(), updatedAt: new Date() },
  { id: 5312, provinsiId: 53, nama: "KABUPATEN NGADA", createdAt: new Date(), updatedAt: new Date() },
  { id: 5313, provinsiId: 53, nama: "KABUPATEN MANGGARAI", createdAt: new Date(), updatedAt: new Date() },
  { id: 5314, provinsiId: 53, nama: "KABUPATEN ROTE NDAO", createdAt: new Date(), updatedAt: new Date() },
  { id: 5315, provinsiId: 53, nama: "KABUPATEN MANGGARAI BARAT", createdAt: new Date(), updatedAt: new Date() },
  { id: 5316, provinsiId: 53, nama: "KABUPATEN SUMBA TENGAH", createdAt: new Date(), updatedAt: new Date() },
  { id: 5317, provinsiId: 53, nama: "KABUPATEN SUMBA BARAT DAYA", createdAt: new Date(), updatedAt: new Date() },
  { id: 5318, provinsiId: 53, nama: "KABUPATEN NAGEKEO", createdAt: new Date(), updatedAt: new Date() },
  { id: 5319, provinsiId: 53, nama: "KABUPATEN MANGGARAI TIMUR", createdAt: new Date(), updatedAt: new Date() },
  { id: 5320, provinsiId: 53, nama: "KABUPATEN SABU RAIJUA", createdAt: new Date(), updatedAt: new Date() },
  { id: 5321, provinsiId: 53, nama: "KABUPATEN MALAKA", createdAt: new Date(), updatedAt: new Date() },
  { id: 5371, provinsiId: 53, nama: "KOTA KUPANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 6101, provinsiId: 61, nama: "KABUPATEN SAMBAS", createdAt: new Date(), updatedAt: new Date() },
  { id: 6102, provinsiId: 61, nama: "KABUPATEN BENGKAYANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 6103, provinsiId: 61, nama: "KABUPATEN LANDAK", createdAt: new Date(), updatedAt: new Date() },
  { id: 6104, provinsiId: 61, nama: "KABUPATEN MEMPAWAH", createdAt: new Date(), updatedAt: new Date() },
  { id: 6105, provinsiId: 61, nama: "KABUPATEN SANGGAU", createdAt: new Date(), updatedAt: new Date() },
  { id: 6106, provinsiId: 61, nama: "KABUPATEN KETAPANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 6107, provinsiId: 61, nama: "KABUPATEN SINTANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 6108, provinsiId: 61, nama: "KABUPATEN KAPUAS HULU", createdAt: new Date(), updatedAt: new Date() },
  { id: 6109, provinsiId: 61, nama: "KABUPATEN SEKADAU", createdAt: new Date(), updatedAt: new Date() },
  { id: 6110, provinsiId: 61, nama: "KABUPATEN MELAWI", createdAt: new Date(), updatedAt: new Date() },
  { id: 6111, provinsiId: 61, nama: "KABUPATEN KAYONG UTARA", createdAt: new Date(), updatedAt: new Date() },
  { id: 6112, provinsiId: 61, nama: "KABUPATEN KUBU RAYA", createdAt: new Date(), updatedAt: new Date() },
  { id: 6171, provinsiId: 61, nama: "KOTA PONTIANAK", createdAt: new Date(), updatedAt: new Date() },
  { id: 6172, provinsiId: 61, nama: "KOTA SINGKAWANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 6201, provinsiId: 62, nama: "KABUPATEN KOTAWARINGIN BARAT", createdAt: new Date(), updatedAt: new Date() },
  { id: 6202, provinsiId: 62, nama: "KABUPATEN KOTAWARINGIN TIMUR", createdAt: new Date(), updatedAt: new Date() },
  { id: 6203, provinsiId: 62, nama: "KABUPATEN KAPUAS", createdAt: new Date(), updatedAt: new Date() },
  { id: 6204, provinsiId: 62, nama: "KABUPATEN BARITO SELATAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 6205, provinsiId: 62, nama: "KABUPATEN BARITO UTARA", createdAt: new Date(), updatedAt: new Date() },
  { id: 6206, provinsiId: 62, nama: "KABUPATEN SUKAMARA", createdAt: new Date(), updatedAt: new Date() },
  { id: 6207, provinsiId: 62, nama: "KABUPATEN LAMANDAU", createdAt: new Date(), updatedAt: new Date() },
  { id: 6208, provinsiId: 62, nama: "KABUPATEN SERUYAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 6209, provinsiId: 62, nama: "KABUPATEN KATINGAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 6210, provinsiId: 62, nama: "KABUPATEN PULANG PISAU", createdAt: new Date(), updatedAt: new Date() },
  { id: 6211, provinsiId: 62, nama: "KABUPATEN GUNUNG MAS", createdAt: new Date(), updatedAt: new Date() },
  { id: 6212, provinsiId: 62, nama: "KABUPATEN BARITO TIMUR", createdAt: new Date(), updatedAt: new Date() },
  { id: 6213, provinsiId: 62, nama: "KABUPATEN MURUNG RAYA", createdAt: new Date(), updatedAt: new Date() },
  { id: 6271, provinsiId: 62, nama: "KOTA PALANGKA RAYA", createdAt: new Date(), updatedAt: new Date() },
  { id: 6301, provinsiId: 63, nama: "KABUPATEN TANAH LAUT", createdAt: new Date(), updatedAt: new Date() },
  { id: 6302, provinsiId: 63, nama: "KABUPATEN KOTA BARU", createdAt: new Date(), updatedAt: new Date() },
  { id: 6303, provinsiId: 63, nama: "KABUPATEN BANJAR", createdAt: new Date(), updatedAt: new Date() },
  { id: 6304, provinsiId: 63, nama: "KABUPATEN BARITO KUALA", createdAt: new Date(), updatedAt: new Date() },
  { id: 6305, provinsiId: 63, nama: "KABUPATEN TAPIN", createdAt: new Date(), updatedAt: new Date() },
  { id: 6306, provinsiId: 63, nama: "KABUPATEN HULU SUNGAI SELATAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 6307, provinsiId: 63, nama: "KABUPATEN HULU SUNGAI TENGAH", createdAt: new Date(), updatedAt: new Date() },
  { id: 6308, provinsiId: 63, nama: "KABUPATEN HULU SUNGAI UTARA", createdAt: new Date(), updatedAt: new Date() },
  { id: 6309, provinsiId: 63, nama: "KABUPATEN TABALONG", createdAt: new Date(), updatedAt: new Date() },
  { id: 6310, provinsiId: 63, nama: "KABUPATEN TANAH BUMBU", createdAt: new Date(), updatedAt: new Date() },
  { id: 6311, provinsiId: 63, nama: "KABUPATEN BALANGAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 6371, provinsiId: 63, nama: "KOTA BANJARMASIN", createdAt: new Date(), updatedAt: new Date() },
  { id: 6372, provinsiId: 63, nama: "KOTA BANJAR BARU", createdAt: new Date(), updatedAt: new Date() },
  { id: 6401, provinsiId: 64, nama: "KABUPATEN PASER", createdAt: new Date(), updatedAt: new Date() },
  { id: 6402, provinsiId: 64, nama: "KABUPATEN KUTAI BARAT", createdAt: new Date(), updatedAt: new Date() },
  { id: 6403, provinsiId: 64, nama: "KABUPATEN KUTAI KARTANEGARA", createdAt: new Date(), updatedAt: new Date() },
  { id: 6404, provinsiId: 64, nama: "KABUPATEN KUTAI TIMUR", createdAt: new Date(), updatedAt: new Date() },
  { id: 6405, provinsiId: 64, nama: "KABUPATEN BERAU", createdAt: new Date(), updatedAt: new Date() },
  { id: 6409, provinsiId: 64, nama: "KABUPATEN PENAJAM PASER UTARA", createdAt: new Date(), updatedAt: new Date() },
  { id: 6411, provinsiId: 64, nama: "KABUPATEN MAHAKAM HULU", createdAt: new Date(), updatedAt: new Date() },
  { id: 6471, provinsiId: 64, nama: "KOTA BALIKPAPAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 6472, provinsiId: 64, nama: "KOTA SAMARINDA", createdAt: new Date(), updatedAt: new Date() },
  { id: 6474, provinsiId: 64, nama: "KOTA BONTANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 6501, provinsiId: 65, nama: "KABUPATEN MALINAU", createdAt: new Date(), updatedAt: new Date() },
  { id: 6502, provinsiId: 65, nama: "KABUPATEN BULUNGAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 6503, provinsiId: 65, nama: "KABUPATEN TANA TIDUNG", createdAt: new Date(), updatedAt: new Date() },
  { id: 6504, provinsiId: 65, nama: "KABUPATEN NUNUKAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 6571, provinsiId: 65, nama: "KOTA TARAKAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 7101, provinsiId: 71, nama: "KABUPATEN BOLAANG MONGONDOW", createdAt: new Date(), updatedAt: new Date() },
  { id: 7102, provinsiId: 71, nama: "KABUPATEN MINAHASA", createdAt: new Date(), updatedAt: new Date() },
  { id: 7103, provinsiId: 71, nama: "KABUPATEN KEPULAUAN SANGIHE", createdAt: new Date(), updatedAt: new Date() },
  { id: 7104, provinsiId: 71, nama: "KABUPATEN KEPULAUAN TALAUD", createdAt: new Date(), updatedAt: new Date() },
  { id: 7105, provinsiId: 71, nama: "KABUPATEN MINAHASA SELATAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 7106, provinsiId: 71, nama: "KABUPATEN MINAHASA UTARA", createdAt: new Date(), updatedAt: new Date() },
  { id: 7107, provinsiId: 71, nama: "KABUPATEN BOLAANG MONGONDOW UTARA", createdAt: new Date(), updatedAt: new Date() },
  { id: 7108, provinsiId: 71, nama: "KABUPATEN SIAU TAGULANDANG BIARO", createdAt: new Date(), updatedAt: new Date() },
  { id: 7109, provinsiId: 71, nama: "KABUPATEN MINAHASA TENGGARA", createdAt: new Date(), updatedAt: new Date() },
  { id: 7110, provinsiId: 71, nama: "KABUPATEN BOLAANG MONGONDOW SELATAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 7111, provinsiId: 71, nama: "KABUPATEN BOLAANG MONGONDOW TIMUR", createdAt: new Date(), updatedAt: new Date() },
  { id: 7171, provinsiId: 71, nama: "KOTA MANADO", createdAt: new Date(), updatedAt: new Date() },
  { id: 7172, provinsiId: 71, nama: "KOTA BITUNG", createdAt: new Date(), updatedAt: new Date() },
  { id: 7173, provinsiId: 71, nama: "KOTA TOMOHON", createdAt: new Date(), updatedAt: new Date() },
  { id: 7174, provinsiId: 71, nama: "KOTA KOTAMOBAGU", createdAt: new Date(), updatedAt: new Date() },
  { id: 7201, provinsiId: 72, nama: "KABUPATEN BANGGAI KEPULAUAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 7202, provinsiId: 72, nama: "KABUPATEN BANGGAI", createdAt: new Date(), updatedAt: new Date() },
  { id: 7203, provinsiId: 72, nama: "KABUPATEN MOROWALI", createdAt: new Date(), updatedAt: new Date() },
  { id: 7204, provinsiId: 72, nama: "KABUPATEN POSO", createdAt: new Date(), updatedAt: new Date() },
  { id: 7205, provinsiId: 72, nama: "KABUPATEN DONGGALA", createdAt: new Date(), updatedAt: new Date() },
  { id: 7206, provinsiId: 72, nama: "KABUPATEN TOLI-TOLI", createdAt: new Date(), updatedAt: new Date() },
  { id: 7207, provinsiId: 72, nama: "KABUPATEN BUOL", createdAt: new Date(), updatedAt: new Date() },
  { id: 7208, provinsiId: 72, nama: "KABUPATEN PARIGI MOUTONG", createdAt: new Date(), updatedAt: new Date() },
  { id: 7209, provinsiId: 72, nama: "KABUPATEN TOJO UNA-UNA", createdAt: new Date(), updatedAt: new Date() },
  { id: 7210, provinsiId: 72, nama: "KABUPATEN SIGI", createdAt: new Date(), updatedAt: new Date() },
  { id: 7211, provinsiId: 72, nama: "KABUPATEN BANGGAI LAUT", createdAt: new Date(), updatedAt: new Date() },
  { id: 7212, provinsiId: 72, nama: "KABUPATEN MOROWALI UTARA", createdAt: new Date(), updatedAt: new Date() },
  { id: 7271, provinsiId: 72, nama: "KOTA PALU", createdAt: new Date(), updatedAt: new Date() },
  { id: 7301, provinsiId: 73, nama: "KABUPATEN KEPULAUAN SELAYAR", createdAt: new Date(), updatedAt: new Date() },
  { id: 7302, provinsiId: 73, nama: "KABUPATEN BULUKUMBA", createdAt: new Date(), updatedAt: new Date() },
  { id: 7303, provinsiId: 73, nama: "KABUPATEN BANTAENG", createdAt: new Date(), updatedAt: new Date() },
  { id: 7304, provinsiId: 73, nama: "KABUPATEN JENEPONTO", createdAt: new Date(), updatedAt: new Date() },
  { id: 7305, provinsiId: 73, nama: "KABUPATEN TAKALAR", createdAt: new Date(), updatedAt: new Date() },
  { id: 7306, provinsiId: 73, nama: "KABUPATEN GOWA", createdAt: new Date(), updatedAt: new Date() },
  { id: 7307, provinsiId: 73, nama: "KABUPATEN SINJAI", createdAt: new Date(), updatedAt: new Date() },
  { id: 7308, provinsiId: 73, nama: "KABUPATEN MAROS", createdAt: new Date(), updatedAt: new Date() },
  { id: 7309, provinsiId: 73, nama: "KABUPATEN PANGKAJENE DAN KEPULAUAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 7310, provinsiId: 73, nama: "KABUPATEN BARRU", createdAt: new Date(), updatedAt: new Date() },
  { id: 7311, provinsiId: 73, nama: "KABUPATEN BONE", createdAt: new Date(), updatedAt: new Date() },
  { id: 7312, provinsiId: 73, nama: "KABUPATEN SOPPENG", createdAt: new Date(), updatedAt: new Date() },
  { id: 7313, provinsiId: 73, nama: "KABUPATEN WAJO", createdAt: new Date(), updatedAt: new Date() },
  { id: 7314, provinsiId: 73, nama: "KABUPATEN SIDENRENG RAPPANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 7315, provinsiId: 73, nama: "KABUPATEN PINRANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 7316, provinsiId: 73, nama: "KABUPATEN ENREKANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 7317, provinsiId: 73, nama: "KABUPATEN LUWU", createdAt: new Date(), updatedAt: new Date() },
  { id: 7318, provinsiId: 73, nama: "KABUPATEN TANA TORAJA", createdAt: new Date(), updatedAt: new Date() },
  { id: 7322, provinsiId: 73, nama: "KABUPATEN LUWU UTARA", createdAt: new Date(), updatedAt: new Date() },
  { id: 7325, provinsiId: 73, nama: "KABUPATEN LUWU TIMUR", createdAt: new Date(), updatedAt: new Date() },
  { id: 7326, provinsiId: 73, nama: "KABUPATEN TORAJA UTARA", createdAt: new Date(), updatedAt: new Date() },
  { id: 7371, provinsiId: 73, nama: "KOTA MAKASSAR", createdAt: new Date(), updatedAt: new Date() },
  { id: 7372, provinsiId: 73, nama: "KOTA PAREPARE", createdAt: new Date(), updatedAt: new Date() },
  { id: 7373, provinsiId: 73, nama: "KOTA PALOPO", createdAt: new Date(), updatedAt: new Date() },
  { id: 7401, provinsiId: 74, nama: "KABUPATEN BUTON", createdAt: new Date(), updatedAt: new Date() },
  { id: 7402, provinsiId: 74, nama: "KABUPATEN MUNA", createdAt: new Date(), updatedAt: new Date() },
  { id: 7403, provinsiId: 74, nama: "KABUPATEN KONAWE", createdAt: new Date(), updatedAt: new Date() },
  { id: 7404, provinsiId: 74, nama: "KABUPATEN KOLAKA", createdAt: new Date(), updatedAt: new Date() },
  { id: 7405, provinsiId: 74, nama: "KABUPATEN KONAWE SELATAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 7406, provinsiId: 74, nama: "KABUPATEN BOMBANA", createdAt: new Date(), updatedAt: new Date() },
  { id: 7407, provinsiId: 74, nama: "KABUPATEN WAKATOBI", createdAt: new Date(), updatedAt: new Date() },
  { id: 7408, provinsiId: 74, nama: "KABUPATEN KOLAKA UTARA", createdAt: new Date(), updatedAt: new Date() },
  { id: 7409, provinsiId: 74, nama: "KABUPATEN BUTON UTARA", createdAt: new Date(), updatedAt: new Date() },
  { id: 7410, provinsiId: 74, nama: "KABUPATEN KONAWE UTARA", createdAt: new Date(), updatedAt: new Date() },
  { id: 7411, provinsiId: 74, nama: "KABUPATEN KOLAKA TIMUR", createdAt: new Date(), updatedAt: new Date() },
  { id: 7412, provinsiId: 74, nama: "KABUPATEN KONAWE KEPULAUAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 7413, provinsiId: 74, nama: "KABUPATEN MUNA BARAT", createdAt: new Date(), updatedAt: new Date() },
  { id: 7414, provinsiId: 74, nama: "KABUPATEN BUTON TENGAH", createdAt: new Date(), updatedAt: new Date() },
  { id: 7415, provinsiId: 74, nama: "KABUPATEN BUTON SELATAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 7471, provinsiId: 74, nama: "KOTA KENDARI", createdAt: new Date(), updatedAt: new Date() },
  { id: 7472, provinsiId: 74, nama: "KOTA BAUBAU", createdAt: new Date(), updatedAt: new Date() },
  { id: 7501, provinsiId: 75, nama: "KABUPATEN BOALEMO", createdAt: new Date(), updatedAt: new Date() },
  { id: 7502, provinsiId: 75, nama: "KABUPATEN GORONTALO", createdAt: new Date(), updatedAt: new Date() },
  { id: 7503, provinsiId: 75, nama: "KABUPATEN POHUWATO", createdAt: new Date(), updatedAt: new Date() },
  { id: 7504, provinsiId: 75, nama: "KABUPATEN BONE BOLANGO", createdAt: new Date(), updatedAt: new Date() },
  { id: 7505, provinsiId: 75, nama: "KABUPATEN GORONTALO UTARA", createdAt: new Date(), updatedAt: new Date() },
  { id: 7571, provinsiId: 75, nama: "KOTA GORONTALO", createdAt: new Date(), updatedAt: new Date() },
  { id: 7601, provinsiId: 76, nama: "KABUPATEN MAJENE", createdAt: new Date(), updatedAt: new Date() },
  { id: 7602, provinsiId: 76, nama: "KABUPATEN POLEWALI MANDAR", createdAt: new Date(), updatedAt: new Date() },
  { id: 7603, provinsiId: 76, nama: "KABUPATEN MAMASA", createdAt: new Date(), updatedAt: new Date() },
  { id: 7604, provinsiId: 76, nama: "KABUPATEN MAMUJU", createdAt: new Date(), updatedAt: new Date() },
  { id: 7605, provinsiId: 76, nama: "KABUPATEN MAMUJU UTARA", createdAt: new Date(), updatedAt: new Date() },
  { id: 7606, provinsiId: 76, nama: "KABUPATEN MAMUJU TENGAH", createdAt: new Date(), updatedAt: new Date() },
  { id: 8101, provinsiId: 81, nama: "KABUPATEN MALUKU TENGGARA BARAT", createdAt: new Date(), updatedAt: new Date() },
  { id: 8102, provinsiId: 81, nama: "KABUPATEN MALUKU TENGGARA", createdAt: new Date(), updatedAt: new Date() },
  { id: 8103, provinsiId: 81, nama: "KABUPATEN MALUKU TENGAH", createdAt: new Date(), updatedAt: new Date() },
  { id: 8104, provinsiId: 81, nama: "KABUPATEN BURU", createdAt: new Date(), updatedAt: new Date() },
  { id: 8105, provinsiId: 81, nama: "KABUPATEN KEPULAUAN ARU", createdAt: new Date(), updatedAt: new Date() },
  { id: 8106, provinsiId: 81, nama: "KABUPATEN SERAM BAGIAN BARAT", createdAt: new Date(), updatedAt: new Date() },
  { id: 8107, provinsiId: 81, nama: "KABUPATEN SERAM BAGIAN TIMUR", createdAt: new Date(), updatedAt: new Date() },
  { id: 8108, provinsiId: 81, nama: "KABUPATEN MALUKU BARAT DAYA", createdAt: new Date(), updatedAt: new Date() },
  { id: 8109, provinsiId: 81, nama: "KABUPATEN BURU SELATAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 8171, provinsiId: 81, nama: "KOTA AMBON", createdAt: new Date(), updatedAt: new Date() },
  { id: 8172, provinsiId: 81, nama: "KOTA TUAL", createdAt: new Date(), updatedAt: new Date() },
  { id: 8201, provinsiId: 82, nama: "KABUPATEN HALMAHERA BARAT", createdAt: new Date(), updatedAt: new Date() },
  { id: 8202, provinsiId: 82, nama: "KABUPATEN HALMAHERA TENGAH", createdAt: new Date(), updatedAt: new Date() },
  { id: 8203, provinsiId: 82, nama: "KABUPATEN KEPULAUAN SULA", createdAt: new Date(), updatedAt: new Date() },
  { id: 8204, provinsiId: 82, nama: "KABUPATEN HALMAHERA SELATAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 8205, provinsiId: 82, nama: "KABUPATEN HALMAHERA UTARA", createdAt: new Date(), updatedAt: new Date() },
  { id: 8206, provinsiId: 82, nama: "KABUPATEN HALMAHERA TIMUR", createdAt: new Date(), updatedAt: new Date() },
  { id: 8207, provinsiId: 82, nama: "KABUPATEN PULAU MOROTAI", createdAt: new Date(), updatedAt: new Date() },
  { id: 8208, provinsiId: 82, nama: "KABUPATEN PULAU TALIABU", createdAt: new Date(), updatedAt: new Date() },
  { id: 8271, provinsiId: 82, nama: "KOTA TERNATE", createdAt: new Date(), updatedAt: new Date() },
  { id: 8272, provinsiId: 82, nama: "KOTA TIDORE KEPULAUAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 9101, provinsiId: 91, nama: "KABUPATEN FAKFAK", createdAt: new Date(), updatedAt: new Date() },
  { id: 9102, provinsiId: 91, nama: "KABUPATEN KAIMANA", createdAt: new Date(), updatedAt: new Date() },
  { id: 9103, provinsiId: 91, nama: "KABUPATEN TELUK WONDAMA", createdAt: new Date(), updatedAt: new Date() },
  { id: 9104, provinsiId: 91, nama: "KABUPATEN TELUK BINTUNI", createdAt: new Date(), updatedAt: new Date() },
  { id: 9105, provinsiId: 91, nama: "KABUPATEN MANOKWARI", createdAt: new Date(), updatedAt: new Date() },
  { id: 9106, provinsiId: 91, nama: "KABUPATEN SORONG SELATAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 9107, provinsiId: 91, nama: "KABUPATEN SORONG", createdAt: new Date(), updatedAt: new Date() },
  { id: 9108, provinsiId: 91, nama: "KABUPATEN RAJA AMPAT", createdAt: new Date(), updatedAt: new Date() },
  { id: 9109, provinsiId: 91, nama: "KABUPATEN TAMBRAUW", createdAt: new Date(), updatedAt: new Date() },
  { id: 9110, provinsiId: 91, nama: "KABUPATEN MAYBRAT", createdAt: new Date(), updatedAt: new Date() },
  { id: 9111, provinsiId: 91, nama: "KABUPATEN MANOKWARI SELATAN", createdAt: new Date(), updatedAt: new Date() },
  { id: 9112, provinsiId: 91, nama: "KABUPATEN PEGUNUNGAN ARFAK", createdAt: new Date(), updatedAt: new Date() },
  { id: 9171, provinsiId: 91, nama: "KOTA SORONG", createdAt: new Date(), updatedAt: new Date() },
  { id: 9401, provinsiId: 94, nama: "KABUPATEN MERAUKE", createdAt: new Date(), updatedAt: new Date() },
  { id: 9402, provinsiId: 94, nama: "KABUPATEN JAYAWIJAYA", createdAt: new Date(), updatedAt: new Date() },
  { id: 9403, provinsiId: 94, nama: "KABUPATEN JAYAPURA", createdAt: new Date(), updatedAt: new Date() },
  { id: 9404, provinsiId: 94, nama: "KABUPATEN NABIRE", createdAt: new Date(), updatedAt: new Date() },
  { id: 9408, provinsiId: 94, nama: "KABUPATEN KEPULAUAN YAPEN", createdAt: new Date(), updatedAt: new Date() },
  { id: 9409, provinsiId: 94, nama: "KABUPATEN BIAK NUMFOR", createdAt: new Date(), updatedAt: new Date() },
  { id: 9410, provinsiId: 94, nama: "KABUPATEN PANIAI", createdAt: new Date(), updatedAt: new Date() },
  { id: 9411, provinsiId: 94, nama: "KABUPATEN PUNCAK JAYA", createdAt: new Date(), updatedAt: new Date() },
  { id: 9412, provinsiId: 94, nama: "KABUPATEN MIMIKA", createdAt: new Date(), updatedAt: new Date() },
  { id: 9413, provinsiId: 94, nama: "KABUPATEN BOVEN DIGOEL", createdAt: new Date(), updatedAt: new Date() },
  { id: 9414, provinsiId: 94, nama: "KABUPATEN MAPPI", createdAt: new Date(), updatedAt: new Date() },
  { id: 9415, provinsiId: 94, nama: "KABUPATEN ASMAT", createdAt: new Date(), updatedAt: new Date() },
  { id: 9416, provinsiId: 94, nama: "KABUPATEN YAHUKIMO", createdAt: new Date(), updatedAt: new Date() },
  { id: 9417, provinsiId: 94, nama: "KABUPATEN PEGUNUNGAN BINTANG", createdAt: new Date(), updatedAt: new Date() },
  { id: 9418, provinsiId: 94, nama: "KABUPATEN TOLIKARA", createdAt: new Date(), updatedAt: new Date() },
  { id: 9419, provinsiId: 94, nama: "KABUPATEN SARMI", createdAt: new Date(), updatedAt: new Date() },
  { id: 9420, provinsiId: 94, nama: "KABUPATEN KEEROM", createdAt: new Date(), updatedAt: new Date() },
  { id: 9426, provinsiId: 94, nama: "KABUPATEN WAROPEN", createdAt: new Date(), updatedAt: new Date() },
  { id: 9427, provinsiId: 94, nama: "KABUPATEN SUPIORI", createdAt: new Date(), updatedAt: new Date() },
  { id: 9428, provinsiId: 94, nama: "KABUPATEN MAMBERAMO RAYA", createdAt: new Date(), updatedAt: new Date() },
  { id: 9429, provinsiId: 94, nama: "KABUPATEN NDUGA", createdAt: new Date(), updatedAt: new Date() },
  { id: 9430, provinsiId: 94, nama: "KABUPATEN LANNY JAYA", createdAt: new Date(), updatedAt: new Date() },
  { id: 9431, provinsiId: 94, nama: "KABUPATEN MAMBERAMO TENGAH", createdAt: new Date(), updatedAt: new Date() },
  { id: 9432, provinsiId: 94, nama: "KABUPATEN YALIMO", createdAt: new Date(), updatedAt: new Date() },
  { id: 9433, provinsiId: 94, nama: "KABUPATEN PUNCAK", createdAt: new Date(), updatedAt: new Date() },
  { id: 9434, provinsiId: 94, nama: "KABUPATEN DOGIYAI", createdAt: new Date(), updatedAt: new Date() },
  { id: 9435, provinsiId: 94, nama: "KABUPATEN INTAN JAYA", createdAt: new Date(), updatedAt: new Date() },
  { id: 9436, provinsiId: 94, nama: "KABUPATEN DEIYAI", createdAt: new Date(), updatedAt: new Date() },
  { id: 9471, provinsiId: 94, nama: "KOTA JAYAPURA", createdAt: new Date(), updatedAt: new Date() },
];

module.exports = kabupaten;
