const provinsi = [
  { id: 11, nama: "ACEH", createdAt: new Date(), updatedAt: new Date() },
  {
    id: 12,
    nama: "SUMATERA UTARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 13,
    nama: "SUMATERA BARAT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { id: 14, nama: "RIAU", createdAt: new Date(), updatedAt: new Date() },
  { id: 15, nama: "JAMBI", createdAt: new Date(), updatedAt: new Date() },
  {
    id: 16,
    nama: "SUMATERA SELATAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { id: 17, nama: "BENGKULU", createdAt: new Date(), updatedAt: new Date() },
  { id: 18, nama: "LAMPUNG", createdAt: new Date(), updatedAt: new Date() },
  {
    id: 19,
    nama: "KEPULAUAN BANGKA BELITUNG",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 21,
    nama: "KEPULAUAN RIAU",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { id: 31, nama: "DKI JAKARTA", createdAt: new Date(), updatedAt: new Date() },
  { id: 32, nama: "JAWA BARAT", createdAt: new Date(), updatedAt: new Date() },
  { id: 33, nama: "JAWA TENGAH", createdAt: new Date(), updatedAt: new Date() },
  {
    id: 34,
    nama: "DI YOGYAKARTA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { id: 35, nama: "JAWA TIMUR", createdAt: new Date(), updatedAt: new Date() },
  { id: 36, nama: "BANTEN", createdAt: new Date(), updatedAt: new Date() },
  { id: 51, nama: "BALI", createdAt: new Date(), updatedAt: new Date() },
  {
    id: 52,
    nama: "NUSA TENGGARA BARAT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 53,
    nama: "NUSA TENGGARA TIMUR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 61,
    nama: "KALIMANTAN BARAT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 62,
    nama: "KALIMANTAN TENGAH",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 63,
    nama: "KALIMANTAN SELATAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 64,
    nama: "KALIMANTAN TIMUR",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 65,
    nama: "KALIMANTAN UTARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 71,
    nama: "SULAWESI UTARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 72,
    nama: "SULAWESI TENGAH",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 73,
    nama: "SULAWESI SELATAN",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 74,
    nama: "SULAWESI TENGGARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { id: 75, nama: "GORONTALO", createdAt: new Date(), updatedAt: new Date() },
  {
    id: 76,
    nama: "SULAWESI BARAT",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { id: 81, nama: "MALUKU", createdAt: new Date(), updatedAt: new Date() },
  {
    id: 82,
    nama: "MALUKU UTARA",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  { id: 91, nama: "PAPUA BARAT", createdAt: new Date(), updatedAt: new Date() },
  { id: 94, nama: "PAPUA", createdAt: new Date(), updatedAt: new Date() },
];

module.exports = provinsi;
